name: 部署服务器

on:
  push:
    branches:
      - main  # 监听main分支的push事件

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true  # 启用调试模式（关键）
          script: |
            cd /home/ec2-user/project/fishtime  # 项目目录
            git pull origin main
            yarn install
            yarn build
            sudo systemctl restart nginx